fix: use cellWidget instead of item for FilterComboBox in UTE editor build
- Column 3 in creatureTable contains a FilterComboBox widget, not a QTableWidgetItem
- add_creature() uses setCellWidget() to set column 3 as a widget
- build() was incorrectly using item() which returns None for widget cells
- Changed to use cellWidget() to correctly retrieve the FilterComboBox widget
- Fixes AttributeError: 'NoneType' object has no attribute 'currentText'